version: "3.9"

name: zazaman

services:
    app:
        container_name: app
        build:
            context: ./php
            network: host
        ports:
            - "9000:9000"
        volumes:
            - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./../:/var/www
        working_dir: /var/www
        networks:
            - backend
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./../:/var/www
        networks:
            - backend
    db:
        container_name: db
        image: mysql:8.0
        networks:
            - backend
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: password
    minio:
        container_name: minio
        image: quay.io/minio/minio
        command: server /data --console-address ":9001"
        ports:
            - "9001:9001"
            - "9005:9005"
        volumes:
            - ./minio/data:/data
        environment:
            MINIO_ROOT_USER: "minioadmin"
            MINIO_ROOT_PASSWORD: "minioadmin"
            MINIO_DEFAULT_BUCKETS: "test"
        networks:
            - backend
    createbuckets:
        image: minio/mc
        networks:
            - backend
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc alias set myminio http://minio:9001 minioadmin minioadmin;
            /usr/bin/mc mb myminio/test;
            /usr/bin/mc policy set public myminio/test;
            exit 0;
            "

networks:
    backend:
        name: backend
